sudo: required
language: node_js
node_js:
  - "10"
cache:
  bundler: false
  yarn: true
  directories:
    - .build-cache
    - ~/.cache
git:
  submodules: false
install: yarn install --frozen-lockfile --non-interactive --audit --silent

jobs:
  include:
    - stage: cache
      name: "Prepare cache"
      script: true
    - stage: test
      name: "Unit tests and code checks"
      script:
        - yarn format:check
        - yarn lint
        - yarn test
    - stage: test
      name: "E2E tests"
      script: yarn e2e:ci
    - stage: build
      language: bash
      name: "Build the docker image"
      node_js:
      services:
        - docker
      install: skip
      script: RELEASE_VERSION=latest ./make-web.sh --build-ml
      after_success: |
        if [ "${TRAVIS_BRANCH}" == "master" ]; then
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag flogo/flogo-web:latest flogo/flogo-web:unstable
          docker push flogo/flogo-web:unstable
          docker tag flogo/flogo-web:latest-ml flogo/flogo-web:unstable-ml
          docker push flogo/flogo-web:unstable-ml
        fi
