export const TYPE_ATTR_ASSIGNMENT = 1;
export const TYPE_LITERAL_ASSIGNMENT = 2;
export const TYPE_EXPRESSION_ASSIGNMENT = 3;
export const VALID_TYPES = [
  TYPE_ATTR_ASSIGNMENT,
  TYPE_LITERAL_ASSIGNMENT
  // TYPE_EXPRESSION_ASSIGNMENT // not yet
];
